# Generated by Django 2.2.7 on 2019-11-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='is_established',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='pub_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='pub_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='source',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='target_period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='pub_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='pub_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='accounting_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
