# Generated by Django 2.2.6 on 2019-11-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20191116_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ir_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
