# Generated by Django 2.2.6 on 2019-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20191116_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ir_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shikiho',
            unique_together={('stock_code', 'pub_year', 'pub_month')},
        ),
    ]
