# Generated by Django 2.2.7 on 2019-11-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20191118_1632'),
        ('stock', '0004_auto_20191116_1455'),
    ]

    operations = [
    ]
