# Generated by Django 2.2.6 on 2019-11-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20191116_2255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('stock_code', 'pub_year', 'pub_month', 'target_period')},
        ),
    ]
