# Generated by Django 2.2.6 on 2019-11-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20191117_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='stock_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='stock_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
    ]
