# Generated by Django 2.2.7 on 2019-11-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_merge_20191118_1640'),
        ('stock', '0009_auto_20191118_2251'),
    ]

    operations = [
    ]
