# Generated by Django 2.2.7 on 2019-11-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_merge_20191119_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='is_established',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
