# Generated by Django 2.2.7 on 2019-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20191120_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
