# Generated by Django 2.2.7 on 2019-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_performance_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='source',
            field=models.IntegerField(choices=[('0', ''), ('1', '四季報'), ('2', '会社発表')]),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='financing_cf',
            field=models.BooleanField(choices=[('', ''), ('True', '+'), ('False', '-')]),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='investing_cf',
            field=models.BooleanField(choices=[('', ''), ('True', '+'), ('False', '-')]),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='operating_cf',
            field=models.BooleanField(choices=[('', ''), ('True', '+'), ('False', '-')]),
        ),
    ]
