# Generated by Django 2.2.7 on 2019-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20191121_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='source',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='financing_cf',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='investing_cf',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='operating_cf',
            field=models.BooleanField(),
        ),
    ]
