# Generated by Django 2.0.9 on 2019-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20191124_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='per',
            field=models.FloatField(null=True),
        ),
    ]
