# Generated by Django 2.0.9 on 2019-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20191126_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='per',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
