# Generated by Django 2.0.9 on 2019-12-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
