# Generated by Django 2.0.9 on 2019-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_note_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='watch_flag',
            field=models.IntegerField(default=0),
        ),
    ]
