# Generated by Django 2.2.7 on 2019-12-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20191218_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='rr_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
