# Generated by Django 2.2.7 on 2019-12-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_auto_20191218_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
