# Generated by Django 2.0.9 on 2019-12-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20191218_2125'),
        ('stock', '0025_note_summary'),
    ]

    operations = [
    ]
