# Generated by Django 2.0.9 on 2020-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_merge_20191218_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='high_limit',
        ),
        migrations.RemoveField(
            model_name='note',
            name='low_limit',
        ),
        migrations.RemoveField(
            model_name='note',
            name='rr_rate',
        ),
        migrations.AddField(
            model_name='note',
            name='buy_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
