# Generated by Django 2.1 on 2020-10-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_auto_20200110_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shikiho',
            name='financing_cf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='investing_cf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shikiho',
            name='operating_cf',
            field=models.IntegerField(),
        ),
    ]
